const MULTIPLIER = Math.pow(2, 24);

/*
 * generateKey
 *
 * Inspired by: https://github.com/facebook/draft-js/blob/67c5e69499e3b0c149ce83b004872afdf4180463/src/model/keys/generateRandomKey.js
 *
 * Note: this still can cause problem as the keys generated by other
 * developers in parallel are not known.
 */
const generateKey = (seenKeys) => {
  let key;
  while (key === undefined || seenKeys.hasOwnProperty(key) || !isNaN(+key)) {
    key = Math.floor(Math.random() * MULTIPLIER).toString(32);
  }
  return key;
};

export default generateKey;
