import mapValues from 'lodash/mapValues';

/*
 * Returns an object containing values generated by the randomValue
 * function of each control.
 */
const randomValues = (properties) => {
  return mapValues(properties, (prop) => {
    console.log(prop);
    return prop.control.type.randomValue({});
  });
};

export default randomValues;
