import mapValues from 'lodash/mapValues';

/*
 * Returns an object containing values generated by the randomValue
 * function of each control.
 */
const randomValues = (properties) => {
  return mapValues(properties, (prop) => {
    if (!(prop.name === 'shape' || prop.type && prop.type.name === 'shape')) {
      return prop.control.type.randomValue(prop);
    }

    const value = prop.value || prop.type.value;
    if (value) {
      return randomValues(value);
    }
  });
};

export default randomValues;
